//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFormsIdentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public int Id { get; set; }
        public Nullable<int> NumberUsers { get; set; }
        public Nullable<System.DateTime> SubscriptionStart { get; set; }
        public Nullable<System.DateTime> Annual { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> SalesRep { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
